# Generated by Django 2.1.2 on 2018-12-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('abstract', models.CharField(max_length=3000)),
                ('body_text', models.CharField(max_length=30000)),
            ],
        ),
    ]
